### ISSUE TITLE
If `--listen` has invalid scheme, receptor will throw traceback

### ISSUE THREAD

**Issue by jeremy-audet** [project-receptor/python-receptor#137] opened 2020-02-18 15:38 UTC
If receptor is started and an invalid scheme is given to a `--listen` flag, then receptor will crash with an unhelpful traceback:

```console
$ poetry run receptor --data-dir="$(mktemp --directory)" node --listen='harglebargle://127.0.0.1:8888'
ERROR 2020-02-18 10:36:39,398  __main__ main: an error occured while running receptor
Traceback (most recent call last):
  File "/home/ichimonji10/code/receptor/receptor/__main__.py", line 59, in main
    config.go()
  File "/home/ichimonji10/code/receptor/receptor/config.py", line 477, in go
    self._parsed_args.func(self)
  File "/home/ichimonji10/code/receptor/receptor/entrypoints.py", line 49, in run_as_node
    controller.enable_server(config.node_listen)
  File "/home/ichimonji10/code/receptor/receptor/controller.py", line 33, in enable_server
    self.loop.create_task(listener)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 431, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
```

It is correct for receptor to bail, but the traceback shown is unhelpful. It would be better if receptor printed a concise message that in some way pointed to the `--listen` flag, rather than complaining about the lack of a coroutine.

**Comment by matburt** [comment] 2020-02-18 15:43
dupe of https://github.com/project-receptor/receptor/issues/93

**Closed as completed by matburt** 2020-02-18 15:43 UTC
